# https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
        generate_for:
          - lib/core/data/models/**/*.dart
          - lib/core/resources/config_model.dart
          - lib/features/**/data/models/**/*.dart

      freezed:
        generate_for:
          - lib/core/business_logic/**/*.dart
          - lib/core/data/models/**/*.dart
          - lib/core/exceptions/exceptions.dart
          - lib/core/resources/config_model.dart
          - lib/features/**/business_logic/*.dart
          - lib/features/**/data/models/**/*.dart

      # https://pub.dev/packages/auto_route#configuring-builders
      auto_route_generator:auto_route_generator: # for @RoutePage
        options:
          enable_cached_builds: true
        generate_for:
          - lib/features/**/presentation/pages/**_page.dart

      auto_route_generator:auto_router_generator: # for @AutoRouterConfig
        generate_for:
          - lib/core/routing/app_router.dart

      graphql_codegen:
        options:
          generatedFileHeader: "// GENERATED CODE - DO NOT MODIFY BY HAND\n\n"
          clients:
            - graphql