name: neat_store_frontend
description: NeatStore Frontend App
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^9.5.0+1
  flutter_stripe_web: ^4.5.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  graphql: ^5.1.3
  http: ^1.1.0
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1
  logger: ^2.0.2+1
  rive: ^0.12.1
  riverpod: ^2.4.5
  shared_preferences: ^2.2.2
  skeletons: ^0.0.3
  synchronized: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  graphql_codegen: ^0.13.7
  import_sorter: ^4.6.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

dependency_overrides:
  collection: ^1.18.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/animations/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

import_sorter:
  comments: false